# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4a61888bac184ac652198f3492c46b7922acdd926f995420c70a8b5672a4fbbfcd15de060d9a075347546564754f63ce85e7b232e8631bd7f5b3212f728d979

test:
  secret_key_base: 936464a1338c06c228ac119aee4b38a9c5d088da4df4ad687f3334229afba3859c3aa894f087ec03a7363d2739df3c2dc5a8dae473b66210d155b863a62e9481

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
